// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzbwdfwwvidoqlrantuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6YndkZnd3dmlkb3FscmFudHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTY3ODIsImV4cCI6MjA3MTM3Mjc4Mn0.vL-5JxpS7xc-RrGUtkm2mlGTg3vkEk_q365ZmNcEaTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});